- client.go
- domains.go
- subdomains.go
- types/domain.go
- types/subdomain.go
This PR updates the domain and subdomain models to match their current structure. It then adds a new endpoint to fetch a subdomain.
> C294 intro autogen subdomains

- app_envs.go
- autogen_subdomains_delegation.go
- client.go
- types/app_env.go
- types/application_environment.go
- types/domain.go
- types/subdomain.go
This PR introduces AppEnvs type and endpoints.
> 302 App env

- autogen_subdomain.go
- autogen_subdomain_delegation.go
- autogen_subdomains.go
- autogen_subdomains_delegation.go
- client.go
- types/autogen_subdomain.go
- types/autogen_subdomain_delegation.go
This PR updates the autogen_subdomains and autogen_subdomain_delegations endpoints to match the changes in furion.
> C307 autogen subdomains

- client.go
- module_versions.go
- modules.go
This PR just adds the modules and module_versions endpoints.
> C338 sync registry

- blocks.go
- blocks_by_name.go
- client.go
- environments.go
- environments_by_name.go
- stacks.go
- stacks_by_name.go
- types/block.go
- types/block_connection.go
- types/environment.go
- types/id_model.go
- types/workspace.go
This PR updates `Block` with https://github.com/nullstone-io/furion/pull/35
This adds `Block.Connections` member.
> 342 Block connections

- autogen_subdomain.go
- autogen_subdomain_delegation.go
- client.go
- domains.go
- domains_by_name.go
- run_configs.go
- subdomains.go
- subdomains_by_name.go
- types/connections.go
- types/workspace_target.go
- workspaces.go
This updates endpoints to align terraform provider with furion changes.
> More furion alignment

- types/workspace.go
Change LastSuccessfulRun to LastFinishedRun
> 299 Ensure module resources and outputs are up-to-date

- blocks_by_name.go
- environments_by_name.go
- stacks_by_name.go
This PR adds the new endpoints to lookup stack, block, and env by name.
> C392 name lookups

- types/capability_config.go
- types/capability_configs.go
- types/run_config.go
This PR adds `CapabilityConfigs` and `CapabilityConfig` which is the data structure used to configure capabilities in a workspace.
> C421 - Adds workspace configuration types for capabilities

- types/capability_config.go
- types/capability_configs.go
- types/run.go
- types/run_config.go
- types/run_targets.go
This PR adds the following:
- Run.IsCleanup
- RunConfig.Targets
- CapabilityConfig.NeedsDestroyed
> c536 cap destroy

- workspace_outputs.go
This PR simply adds the new workspace_outputs#get_latest endpoint to our library.
> C347 sensitive vars

- find/err_multiple_blocks_found.go
- find/stack_and_block_by_name.go
- find/stack_block_env_by_name.go
This PR adds `find` package automating finding resources by name.
> Added find package to search by name for block+env

- app_envs.go
- apps.go
- client.go
- deploys.go
- types/deploy.go
This PR updates go-api-client to match the updated routes and naming of deployments.
> C787 app versions

- deploys.go
- live_logs.go
- module_versions.go
- types/create_run_input.go
- types/dependency_config.go
- types/dependency_configs.go
This PR adds `DependencyConfigs` to `CreateRunInput`.
> C839 fix nullstone up

- deploys.go
- types/deploy.go
This PR simply adds the `reference` field to the deploy model. This is utilized in the deploy process.
> C887 app status

- types/user.go
added a user type to model out its structure
> C1068 finalize auto deploy

- deploys.go
Added "fromSource" input payload to deploy create.
> Added support for deploying from source.

- types/block.go
- types/capability.go
Removing `stackName` and `parentBlocks`.
> C1036 furion perf

- types/app_env.go
- types/deploy.go
Updates are made for https://github.com/nullstone-io/enigma/pull/26
> Update AppEnv, Deploy types with build/deploy metadata

- config.go
- trace/http_transport.go
- trace/is_enabled.go
- trace/tracer.go
- ws/streamer.go
- Fixed nil panic when streaming logs over websocket connection.
- Added client tracing to websocket streaming logs.
> Websocket streaming improvements

- client.go
- env_runs.go
- preview_envs.go
- types/create_env_run_input.go
- types/create_run_input.go
- types/module.go
- workspaces.go
Added 2 new endpoints:
1. preview_envs#create
2. env_runs#create
> C1129 preview envs cli

- client.go
- env_configurations.go
- types/create_run_input.go
Added a new endpoint for env_configurations.
WIP
> F1219 iac file

- app_capabilities.go
- types/capability.go
This PR updates this client to match the endpoints in furion for capabilities. These endpoints are now scoped by env_id.
> F1221 caps by env

- app_capabilities.go
- app_pipeline_capabilities.go
- client.go
Updated all the capability endpoints to match what is now in furion.
> F1313 capabilities without env

- types/block.go
This simply adds the `shared` field to all blocks.
> F1220 shared infra

- types/block.go
- types/connection_target.go
Expand functionality of `ConnectionTarget` to parse, normalize, and match.
> Connection target help

- types/environment.go
Added the IsProd field to the environment.
> F1604 create envs

- client.go
- current_user.go
Added the endpoint for fetching the current user.
> F1748 exec for tasks

- types/connection_target.go
Add yaml marshalling support to ConnectionTarget.
> F1401 export iac file

- block_syncs.go
- types/block.go
This PR adds the `OwningRepo` field to the Block type.
It also adds the block_syncs#create method to the endoints.
> F1760 block ownership

- block_syncs.go
- capability_copies.go
- client.go
- env_infra_configurations.go
- find/resource_resolver.go
- find/resource_resolver_test.go
- find/stack_resolver.go
- pipeline_block_syncs.go
- pipeline_infra_configurations.go
- types/block.go
- types/connection_target.go
Added the new pipeline_block_syncs endpoint. Added capabilities to the block struct so we can pass those around together.
> F1813 gitops processing

- deploys.go
This PR adds a new field to the deploys#create endpoint for commitSha. This matches the addition to the endpoint in enigma.
> F1815 deploy version

- client.go
- workspace_configs.go
This exposes the WorkspaceConfigs resource to the API client.
> Added WorkspaceConfigs

- client.go
- deploys.go
- intent_workflows.go
- runs.go
- runs/create.go
- runs/destroy.go
- runs/launch.go
- types/intent_workflow.go
- types/run.go
- types/stream_object.go
- types/workspace_workflow.go
- types/workspace_workflow_activities.go
- workspace_workflows.go
- ws/stream_object.go
- ws/stream_object_test.go
This includes new endpoints and updates to existing types to work with the new engine.
> Update api client for v3 engine

- types/variable.go
Added helper to Variable to determine when a variable value has been reset back to the default.
> Added Variable.ValueEqualsDefault

- client.go
- response/bad_request_error.go
- response/invalid_request_error.go
- response/not_found_error.go
- subdomain_workspaces.go
- types/subdomain.go
Added endpoint for retrieving subdomain workspace information.
> Subdomain workspaces

- types/build_config.go
Added the config necessary to support Github Actions builder.
> F2079 github actions builder

- types/environment.go
This PR adds the CreatedBy field to the environment to match the furion changes.
> F2121 lots of previews
